[package]
name = "orbital"
version = "0.1.0"
authors = ["Austen LeBeau <austenlebeau@gmail.com>"]
edition = "2018"

[dependencies]
# Print data in an easy to read table
prettytable-rs = "0.8.0"
<<<<<<< HEAD
=======
nalgebra = "0.16.13"
>>>>>>> d4e0cb4d39eed4456062776765052dbc0a668330
